### ISSUE TITLE
Create BranchValidator project and implement action code

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/BranchValidator#1]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description
Create a status check workflow to validate branch name syntax.  This will validate that the branch currently being used will not only be named correctly, but also have a context that makes sense.

---

## **What To Implement**

**Action Inputs:**
- `branch-name`
  - Required: true
  - Default Value: empty string
- `validation-logic`
  - Required: true
  - Default Value: empty string
- `trim-from-start` (Added on 7-Jul-2022)
  - Required: false
  - Default Value: empty string
- `fail-when-not-valid`
  - Required: false
  - Default Value: true

## `branch-name` Input:
An action input named `branch-name` should hold the name of the branch.

## `validation-logic` Input:
The action input named `validation-logic` should be a string that contains a combination of functions with AND and OR logic.
All functions will be case sensitive and will be camel cased.  Functions can have 1 or more arguments.  String arguments will require double quotes and numbers will can only be whole numbers.  They all return `bool` values of `true` or `false`.

## `trim-from-start` Input:
The action input named 'trim-from-start' should be a string that contains the text that will be trimmed from the beginning of the branch name before the validation process begins.  This will make it easier to remove 'string' values from the beginning of the branch in GitHub Actions when using the environment variables for branches such as `github.base_ref`, `github.head_ref`, and `github.ref`

---

## **Examples:**
For example, if the action input had the value **v\*.\*.\*-preview.\***, then this would mean that any branch with the name would be required to start with the letter 'v', 3 periods, and contain the string "-preview." towards the end.
This way, if the branch name parts meet the criteria, they action would return the value of "true" which means the branch is valid.

Also, if the value of the action input could be a list of functions delimited by a **_&&_** or **_||_**.  This would give the ability to perform boolean logic on the results of the functions.  The **_&&_** is for performing AND logic and the **_||_** is for performing OR logic.  The logic is always processed in order from left to right.

**Things to note:**
- Spaces around **_&&_** and **_||_** and other functions are aloud.
- Spaces around argument commas are aloud.
- Make sure to process multi-line strings.  This means that new line and carriage return characters need to be stripped before processing the logic.

**Simple Examples:**
`branch-name` = `master`
`validation-logic` = `equalTo("master") || equalTo("develop")`
Result: true

`branch-name` = `master`
`validation-logic` = `equalTo("master") && equalTo("develop")`
Result: false

**Advanced Example:**
`branch-name` = `v1.2.3-preview.4`
`validation-logic` = `v#.#.#-preview.#`
Result: true

---

### Acceptance Criteria

**This issue is finished when:**

 - [x] All of the functions listed above work correctly to validate the syntax of the branch
 - [x] Displays clear error messages for each function used in the `validation-logic` action input
 - [x] Returns `true` if the branch is valid and `false` if it is not
 - [x] Only fails the job/workflow if the `fail-when-not-valid` is set to `true`

**All functions implemented below:**
  - [x] `equalTo(string value)` implemented
  - [x] `isCharNum(int pos)` implemented
  - [x] `isSectionNum(int startPos, string upToChar)` implemented
  - [x] `isSectionNum(int startPos, int endPos)` implemented
  - [x] `contains(string value)` implemented
  - [x] `notContains(string value)` implemented
  - [x] `existTotal(string value, int total)` implemented
  - [x] `existsLessThan(string value, int amount)` implemented
  - [x] `existsGreaterThan(string value, int amount)` implemented
  - [x] `startsWith(string value)` implemented
  - [x] `notStartsWith(string value)` implemented
  - [x] `endsWith(string value)` implemented
  - [x] `notEndsWith(string value)` implemented
  - [x] `startsWithNum()` implemented
  - [x] `endsWithNum()` implemented
  - [x] `lenLessThan(int length)` implemented
  - [x] `lenGreaterThan(int length)` implemented
  - [x] `isBefore(string value, string after)` implemented
  - [x] `isAfter(string value, string before)` implemented

### ToDo Items

- [x] Priority label added to issue
