### ISSUE TITLE
🚧Add URL link to create issue to console output

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/BranchValidator#10]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Add a URL link to the console output to create an issue for this project.
This will always be printed to the console.  Print this as part of the welcome message.

### Acceptance Criteria

**This issue is finished when:**
- [x] URL link to create issue added to welcome message

### ToDo Items

- [x] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] Issue linked to the correct project.
- [x] Issue linked to the correct milestone.
- [x] Draft pull request created and linked to this issue.

### Related Work

- KinsonDigital/KDActionUtils#23

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                                                                                |
|---------------------|--------------------------------------------------------------------------------------|
| Bug Fixes           | https://github.com/KinsonDigital/BranchValidator/labels/%F0%9F%90%9Bbug                     |
| Breaking Changes    | https://github.com/KinsonDigital/BranchValidator/labels/%F0%9F%A7%A8breaking%20changes      |
| New Features         | https://github.com/KinsonDigital/BranchValidator/labels/%E2%9C%A8new%20feature                         |
| Workflow Changes    | https://github.com/KinsonDigital/BranchValidator/labels/workflow                            |
| Code Doc Changes    | https://github.com/KinsonDigital/BranchValidator/labels/%F0%9F%93%91documentation%2Fcode    |
| Product Doc Changes | https://github.com/KinsonDigital/BranchValidator/labels/%F0%9F%93%9Ddocumentation%2Fproduct |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                              |
|---------------------|--------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/BranchValidator/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/BranchValidator/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/BranchValidator/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
