### ISSUE TITLE
🚧Create validate status check

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/BranchValidator#101]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Create a status check workflow to check for the current set version as well as release notes. 
An example to use for this is the _**version-notes-status-check.yml**_ workflow in the [PackageMonster](https://github.com/KinsonDigital/PackageMonster/blob/master/.github/workflows/version-notes-status-check.yml) project.

> **Note** 
> - Please make sure to look through the workflow to see if anything needs to be changed such as directory and file paths, project-specific information, etc.
> - The cicd scripts to use are in the **Infrastructure** repository

### Acceptance Criteria

- [x] Status check for checking version and release notes added to the project
    - [x] workflow file name is _**version-notes-status-check.yml**_
    - [x] Workflow points to organization-level validation scripts, not local scripts.

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Issue Dependencies

- KinsonDigital/PackageMonster#89

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
