### ISSUE TITLE
🚧Add version and notes status check

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/BranchValidator#103]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Add "not required" status check to workflow. 

> **Note** Use the status check named _**version-notes-status-check.yml**_ in the **_PackageMonster_** project as a guide.

1. Create a new workflow to allow status check pass status when introducing non-code changes.
    - The file name should be _**version-notes-status-check-not-required.yml**_
    - The YAML `name` of the job should be `Version Notes Status Check Not Required`
      ```diff
      jobs:
        version_and_notes_status_check:
      -     name: Version Notes Not Required Status Check
      +     name: Version Notes Status Check Not Required
      ```

### Acceptance Criteria

- [x]  A new workflow has been created to allow status check pass status when introducing non-code changes.
    - [x] File named _**version-notes-status-check-not-required.yml**_
    - [x] The YAML `name` of the job named `Version Notes Status Check Not Required`

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
