### ISSUE TITLE
🚧Update Code of Conduct

### ISSUE THREAD

**Issue by kselena** [KinsonDigital/BranchValidator#16]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update code of conduct file.  Use the file below:
[code_of_conduct.md](https://github.com/KinsonDigital/Velaptor/files/9257952/code_of_conduct.md)

### Acceptance Criteria

**This issue is finished when:**
- [x] Code of Conduct file updated

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.
- [X] Issue linked to the correct milestone.
- [x] Draft pull request created and linked to this issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
