### ISSUE TITLE
🚧Fix broken enhancement label link

### ISSUE THREAD

**Issue by kselena** [KinsonDigital/BranchValidator#17]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

The label was changed but the link is still pointing to the old enhancement label.  The old enhancement label was changed and this is how the link has become broken.

### Acceptance Criteria

**This issue is finished when:**
- [ ] Label link is updated

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.
- [X] Issue linked to the correct milestone.
- [ ] Draft pull request created and linked to this issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Will be implemented in issue below:
- #312
