### ISSUE TITLE
🚧Improve project README

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/BranchValidator#38]
### Complete Items Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Improve the project's readme so the text in the **What's the point? 🤷🏼** section is laid out better.  Currently the way that the text is wrapping is making the layout all **WONKY** and difficult to read.  The assumption is that the markdown is setup to force wrap the sentences instead of auto-wrapping the text.

Either way, it does not look great.

💡Use **VSCode** to view the rendered markdown with the approximately the same width as in the browser in the marketplace, and use this as a guide to layout the text.

**Currently On Marketplace:**
<img width="604" alt="image" src="https://user-images.githubusercontent.com/85414302/186210892-0c5ba6af-9145-4a28-802e-b0b657c54acb.png">

Convert the action input example values to inline code blocks to emphasize what it should look like.
The text to convert are in the purple rectangles in the image below:
![image](https://user-images.githubusercontent.com/85414302/186213827-a9b4e3d5-c61a-453a-93a9-20f8963056f0.png)

### Acceptance Criteria

- [x] Section in README changed to lay out text in a better way
- [x] Input value examples converted into markdown inline code blocks
  - This is done by simply adding a single backtick to each end of the text you want to convert to an inline code block.

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if required)_.
- [X] Issue linked to the correct milestone _(if required)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                                                                                |
|---------------------|--------------------------------------------------------------------------------------|
| Bug Fixes           | https://github.com/KinsonDigital/BranchValidator/labels/%F0%9F%90%9Bbug                     |
| Breaking Changes    | https://github.com/KinsonDigital/BranchValidator/labels/%F0%9F%A7%A8breaking%20changes      |
| New Feature         | https://github.com/KinsonDigital/BranchValidator/labels/%E2%9C%A8new%20feature              |
| Workflow Changes    | https://github.com/KinsonDigital/BranchValidator/labels/workflow                            |
| Code Doc Changes    | https://github.com/KinsonDigital/BranchValidator/labels/%F0%9F%93%91documentation%2Fcode    |
| Product Doc Changes | https://github.com/KinsonDigital/BranchValidator/labels/%F0%9F%93%9Ddocumentation%2Fproduct |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                              |
|---------------------|--------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/BranchValidator/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/BranchValidator/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/BranchValidator/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
@kselena In the picture above with the purple rectangles, the words **Example 1:**, **Example 2:**, etc., do you think those should be italic?

Don't be afraid to come up with some ideas to improve the readability and layout of this document.   You can play around with different things in **VSCode** as well.

**Comment by KinsonDigitalAdmin** [comment]
@kselena Just a quick heads up.  Anytime you change anything that has to do with the product documentation, we need a https://github.com/KinsonDigital/BranchValidator/labels/%F0%9F%93%9Ddocumentation%2Fproduct label.

I went ahead and added one for both the PR and the issue.

It is a little tricky.  If I am adding a new method that has code docs, those code docs end up in the API documentation website., but I will not put the https://github.com/KinsonDigital/BranchValidator/labels/%F0%9F%93%9Ddocumentation%2Fproduct on that issue. The reason is that the https://github.com/KinsonDigital/BranchValidator/labels/%F0%9F%93%9Ddocumentation%2Fproduct is meant only for documentation changes without changes to the original code base.

For example, if I had an issue to ONLY changing the code docs, then that would take the https://github.com/KinsonDigital/BranchValidator/labels/%F0%9F%93%9Ddocumentation%2Fproduct label.
