### ISSUE TITLE
🚧Move release note template files to proper folder

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/BranchValidator#53]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

The release note template files are located in the incorrect location.  These files need to be moved to the folder `~/Documentation/ReleaseNotes/`.

Currently they are located in `~/Documentation/ReleaseNotes/PreviewReleases/`.

This was accidentally missed in the issue below during the code review.
- #48

### Acceptance Criteria

- [x] Release template files moved to proper folder location.

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
