### ISSUE TITLE
🚧Improve console output

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/BranchValidator#56]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Improve the GitHub console output by using some emojis.

For each step, add a ✔️ emoji at the beginning.
If the branch is valid, add the 🥳 emoji to the end.
If the branch is not valid, add the 😞 emoji to the end.

**Placement:**
![image](https://user-images.githubusercontent.com/85414302/187070884-136652a1-416e-4c88-87a9-47d0b70ccf6a.png)

### Acceptance Criteria

- [ ] ✔️ emoji added to the beginning of each processing step
- [ ] 🥳 emoji added to a valid branch message
- [ ] 😡 emoji added to an invalid branch message

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
