### ISSUE TITLE
🚧Fix issue with matching patterns

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/BranchValidator#57]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Currently, the translation between the custom action glob matching syntax and regex syntax has an issue.

feature/setup-build-project
- Value: feature/setup-build-project
- Patter:n  feature/setup-*-project

This was discovered when using the same code while playing around with Nuke build system framework.

The problems are that the globbing pattern needs to always start with a '^' symbol and end with a '$' symbol.

Also, the `RegexOptions.IgnoreCase` needs to NOT be used at all.  Currently, if the value above had a 'T` for the word `project` ad the end, it would still pass.  Remove case sensitivity.

Remove the `MatchType.` enum and its use case as well

### Acceptance Criteria

- [ ] The symbol '^' added to the start of the `globbingPattern` every time in the `Match()` method
- [ ] The symbol '$' added to the end of the `globbingPattern` every time in the `Match()` method
- [ ] Remove the `RegexOptions.IgnoreCase` argument for all `RegEx.Match()` method calls

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
