### ISSUE TITLE
🚧Fix broken badges

### ISSUE THREAD

**Issue by KinsonDigitalAdmin** [KinsonDigital/BranchValidator#74]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Fix the badges and remove unnecessary ones.  The reason that they are showing LINKS is because they are broken.

It is assumed that something changed with the service called [Shields IO](https://shields.io/) has changed causing the issue.
Other repos have been fixed already.

![image](https://user-images.githubusercontent.com/105235056/220628252-c72de4f7-0633-4859-b854-6dc37b353166.png)

Use the badges in Velaptor as a reference.

### Acceptance Criteria

- [x] Badges fixed

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
