### ISSUE TITLE
🚧Update Readme

### ISSUE THREAD

**Issue by kselena** [KinsonDigital/BranchValidator#90]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

## **Description**

We are in the process of rationalizing ReadMe across all GitHub Actions (GHA). This includes:

Making sure all sections are in this order:
  - Logo
  - Repo Name
  - Badges
  - What is it
  - Warning/Note (Quick Note)
  - Example
  - Action Input
  - Action Output
  - Validation Functions 
  - Validation list
  - More Examples
  - Contrib
  - Maintainers
  - License

### **Details of the changes to the sections are below:**

**What is it Section**
- Use what is currently in this section after spelling and grammar checks
- Add what does it do section as a TLDR
  
**Quick Note Section** 
- Change to say Warning block instead of Quick Note

**Quick Example Section**
- Make sure the "more examples below" link is on the right side.

**What does it do? Section**
- Move section to What is it? section at top

**Action Input/Output Section**
-Remove table from Output and make a sentence
-Keep Input section, but make it align left

**Contribution Section**
- Change title to Contributing
- Make it like Velaptor

**Maintainers Section**
- Make section like in Velaptor

**License Section**
- Add section just like in Velaptor; with badges etc.

### **Other**
 - Double checking spelling/grammar
 - Making wording the same in similar sections
 - Make sure "Back to the Top" link is on the right
 - Remove any TODO comments
 - Verify all links work and point correctly
 - Make sure all emoji's are like GotNuget/Velaptor

## Acceptance Criteria
- [x] Make sure all sections are in this order:
    - [x] Logo
    - [x] Repo Name
    - [x] Badges
    - [x] What is it
    - [x] Warning/Note (Quick Note)
    - [x] Example
    - [x] Action Input
    - [x] Action Output
    - [x] Examples
    - [x] Contrib/Funding (after combined like in lib section)
    - [x] Maintainers
    - [x] License
- [x] Perform spelling and grammar checks in the **What is it** section
- [x] Change the **Quick Note** section to Warning block 
- [x]  **More examples below** link is to the right side.
- [x] Move the **What does it do** section to **What is it** section
- [x] Action Output section is a sentence; not a table
- [x] Action Input section is align left
- [x] Update the **Contribution Section**
  - [x] Change the **Contribution** title to **Contributing**
  - [x] Add one link that points to the Contributing doc for time contributions
    - [x] To learn how to contribute your time click `[here](https://github.com/KinsonDigital/.github/blob/master/docs/CONTRIBUTING.md)`
  - [x] Add one link that points to GitHub sponsors for monetary contributions
    - [x] To learn how to contribute funds to this project, click `[here](https://github.com/sponsors/KinsonDigital)`
- [x] Add **Maintainers** section like in Velaptor
- [x] Add **License** section just like in Velaptor; with badges
 - [x] Double check spelling/grammar
 - [x] Making wording the same in other GH Actions and Libraries
 - [x] Remove "Back to the Top" link 
 - [x] Remove any TODO comments
 - [x] Verify all links work and point correctly
 - [x] All emoji's are like GotNuget/Velaptor

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
